[package]
name = "core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "BlipMQ core broker logic: topics, queues, QoS"
license.workspace = true

[lib]
name = "corelib"

[dependencies]
tracing = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
wal = { path = "../wal" }
parking_lot = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
ahash = "0.8"
smallvec = "1"
flume = { version = "0.11", default-features = false, features = ["async"] }
crc32fast = { workspace = true }
hdrhistogram = { version = "7", default-features = false }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "time", "sync"] }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "fanout"
harness = false

